apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: "powerstore-ext4-retain"
provisioner: "csi-powerstore.dellemc.com"
parameters:
  arrayID: "Unique"
  csi.storage.k8s.io/fstype: "ext4"
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
